### ISSUE TITLE
Word Vectors and Distribution

### ISSUE THREAD

**Issue by Sara-Online** [lffloyd/embedded-topic-model#7]
Hi! I successfully used this package but how can I get the word vector, topic vector and the distribution? Thanks

**Comment by lffloyd** [comment]
Hi @Sara-Online, sorry for the (very) late response. Thanks for using this package!

You can get the topic words with this method. Note that you can select how many word per topic you're interest in:
```python
t_w_mtx = etm_instance.get_topics(top_n_words=20)
```

You can get the topic word matrix with this method. Note that it will return all word for each topic:
```python
t_w_mtx = etm_instance.get_topic_word_matrix()
```

You can get the topic word distribution matrix and the document topic distribution matrix with the following methods, both return a normalized distribution matrix:
```python
t_w_dist_mtx = etm_instance.get_topic_word_dist()
d_t_dist_mtx = etm_instance.get_document_topic_dist()
```

I will update the documentation soon detailing these methods.

Cheers,
Luiz

**Comment by lffloyd** [comment]
Documentation updated with #15
