### ISSUE TITLE
Add support for Torch > 1.6.0.

### ISSUE THREAD

**Issue by kjaksic** [lffloyd/embedded-topic-model#8]
Is it possible to add support for torch > 1.6.0 since running the package using 30xx GPUs is not possible (because on these cards cuda 11 is required and first torch version to support it was torch 1.7.0). 

Thank you.

**Comment by lffloyd** [comment]
Hi @kjaksic , sorry for the (very) late response and thanks for your report.

This is a relevant update and should be addressed on the next releases. I will look into that.

Cheers,
Luiz

**Comment by lffloyd** [comment]
Solved by #23 , which updates the library `torch>=2.0.*`

**Comment by kjaksic** [comment]
Great to see the update, thanks!

sri, 6. ruj 2023. u 20:25 Luiz Matos ***@***.***> napisao je:
